on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: .env
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env.local file
        run: |
          echo "DB_USER=${{ DB_USER }}" >> .env.local
          echo "DB_HOST=${{ DB_HOST }}" >> .env.local
          echo "DB_DATABASE=${{ DB_DATABASE }}" >> .env.local
          echo "DB_PASSWORD=${{ DB_PASSWORD }}" >> .env.local
          echo "DB_PORT=${{ DB_PORT }}" >> .env.local
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M%S')"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: namssy/bgm-home:latest,namssy/bgm-home:${{ steps.date.outputs.date }}